### PR TITLE
Monadfail

### LINKED ISSUE #61: No instance for `MonadFail Marshal`
Under a GHC new enough that the `MonadFail` split is complete, the library fails to compile `Data.Ruby.Marshal.Get`:

```ruby-marshal            >  
ruby-marshal            > /run/user/1000/stack-bc4132fd6e708d1d/ruby-marshal-0.1.3/src/Data/Ruby/Marshal/Get.hs:122:20: error:
ruby-marshal            >     • No instance for (MonadFail Marshal) arising from a use of ‘fail’
ruby-marshal            >     • In the expression: fail "expected single character"
ruby-marshal            >       In a stmt of a 'do' block:
ruby-marshal            >         if | len /= 1 -> fail "expected single character"
ruby-marshal            >            | otherwise
ruby-marshal            >                -> do symbol <- g
ruby-marshal            >                      denote <- g
ruby-marshal            >                      ....
ruby-marshal            >       In the second argument of ‘($)’, namely
ruby-marshal            >         ‘do str <- g
ruby-marshal            >             len <- getFixnum
ruby-marshal            >             if | len /= 1 -> fail "expected single character"
ruby-marshal            >                | otherwise -> do ...’
ruby-marshal            >     |
ruby-marshal            > 122 |   if | len /= 1 -> fail "expected single character"
ruby-marshal            >     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ruby-marshal            >  
```

### PR DESCRIPTION
**Pull request by JackKelly-Bellroy**
Closes #61.
This PR adds the `MonadFail` instance to the `Marshal` monad, so that it works with base-4.13.0.0 and above. I haven't updated the version numbers, and leave it to you to cut a new release.

### CODE REVIEW

**Comment by endgame** [comment]
And wearing my non-work, Hackage Trustee hat:

This means that the `base` version bounds on your previous releases are too loose (should be `< 4.13.0.0` instead of `< 5`), and metadata revisions should be published to Hackage for previous releases. I am able to assist with this, or even publish the revisions myself if you'd prefer.

**Comment by JackKelly-Bellroy** [comment]
Annoyingly, we can't derive the MonadFail instances nor provide type signatures for the pattern synonyms if we want to continue supporting GHC 7.10.3. I have added a manual `Monad` and `MonadFail` instance with the necessary CPP, and removed the pattern synonyms. If you want to drop GHC 7.10.3 instead, I will rearrange this branch to give you a simpler PR.

**Comment by mcfilib** [comment]
lgtm! i'll try and put together a release before the weekend.

**Comment by endgame** [comment]
Great, thanks. Let me know if you'd like me to help out with the metadata revisions for previous hackage releases.

**Comment by mcfilib** [comment]
go for it!

**Comment by endgame** [comment]
Done for all versions `< 0.2`. I think the `base <5` on `0.2` is dubious but I'm not aware of other major changes coming down the line for `base`, so I left it alone.

P.S.: Thanks for dealing with this so quickly.
